---
abstract: 'Command Line Interface interface to Google Calendar.'
author:
  - 'Andrew Jones <andrew@arjones.co.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-gcal
requires:
  Class::ReturnValue: 0
  Data::ICal: 0
  DateTime::Format::ICal: 0
  DateTime::TimeZone: 0
  Getopt::Long: 0
  ICal::Format::Natural: 0
  Net::Google::Calendar: 0
  Net::Google::Calendar::Entry: 0
  Net::Netrc: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/andrewrjones/gcal/issues
  homepage: https://github.com/andrewrjones/gcal
  repository: https://github.com/andrewrjones/gcal.git
version: 1.121310
